version: '3'
services:
  openapi-exposedb-safrs:
    image: pcourbin/openapi-exposedb-safrs:2.7.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        safrs_version: 2.7.0
    environment:
      - DB_HOST=db.serveur.fr # Do not define if the DB is accessible on your docker host
      - DB_PORT=3306
      - DB_NAME=mydbname
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - 3000:3000
